config/routes.rb
Rails.application.routes.default_url_options[:host] = "XXX"
Rails.application.routes.draw do

  root 'themes#index'
  get 'themes/index'
  get 'pages/about'
  get 'guestlists_imports/new'
  get 'guestlists_imports/create'
  get '/events/:event_id/guestlists/:id/response_page/:response', to: 'guestlists#response_page'

  #resources :guestlists_imports, only: [:new, :create]
  resources :locations
  #root to: 'events#index'
  root to: redirect('/events')
  root to: redirect('/guestlists')
  root to: redirect('/pages/about')
  #get 'guestlists'
  resources :events do
    resources :guestlists do
      patch :response_page, on: :member
      # match '/response_page', to:'events#guestlist#response_page', as: :response_page, :via => [:get,:post]
      collection do
        post :import
      end
    end
    resources :todo_lists do
      resources :todo_items do
        member do
          patch :complete
        end
      end
    end

    match '/landing_page', to:'events#landing_page', as: :landing_page, :via => [:get,:post]
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
 has_many :todo_items, :dependent => :destroy
 accepts_nested_attributes_for :todo_items

 belongs_to :event

 validates :title, :description, presence: true
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_event
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]

  # GET /todo_lists
  # GET /todo_lists.json
  def index
    @todo_lists = @event.todo_lists.all
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show

  end

  # GET /todo_lists/new
  def new
    @todo_list = TodoList.new
  end

  # GET /todo_lists/1/edit
  def edit
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    @todo_list = @event.todo_lists.new(todo_list_params)

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to event_todo_lists_path(@event), notice: 'To do list was successfully created.' }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1
  # PATCH/PUT /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: 'To do list was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to event_todo_lists_path(@event), notice: 'To do list was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = @event.todo_lists.find(params[:id])
    end

    def set_event
      @event = Event.find(params[:event_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_list_params
      params.require(:todo_list).permit(:title, :description, :event_id)
    end
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/todo_lists/_form.html.erb
<%= form_with(model:[@event, todo_list] , local: true) do |form| %>
  <% if todo_list.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% todo_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/todo_lists/edit.html.erb
<h1 class="todo_list_title">Editing Task List</h1>
<div class="forms">
<%= render 'form', todo_list: @todo_list %>
</div>
<div class="links">
<%= link_to 'Cancel', todo_lists_path %>
</div>

app/views/todo_lists/index.html.erb
<h1>Task Lists for <%= @event.name %></h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Title</th>
      <th scope="col">Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todo_lists.each do |todo_list| %>
      <tr>
        <td><%= todo_list.title %></td>
        <td><%= todo_list.description %></td>
        <td><%= link_to 'Show/Add Tasks', event_todo_list_path(@event, todo_list) %></td>
        <td><%= link_to 'Edit', edit_event_todo_list_path(@event, todo_list) %></td>
        <td><%= link_to 'Delete', event_todo_list_path(@event, todo_list), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task List', new_event_todo_list_path(@event), {:style=>'color:#WWWWWW;', :class => "btnC"} %>  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<%= link_to 'Back to Event', event_path(@event), {:style=>'color:#WWWWWW;', :class => "btnC"} %>

app/views/todo_lists/new.html.erb
<h1 class="todo_list_title">New Task List for <%=@event.name %></h1>
<div class="forms">
<%= render 'form', todo_list: @todo_list %>
</div>
<div class="links">
<%= link_to 'Back', event_todo_lists_path(@event), {:style=>'color:#000000;', :class => "h2"} %>
</div>

app/views/todo_lists/show.html.erb
<h2 class="todo_list_title"><%= @todo_list.title%> for <%=@event.name%></h2>
<p class="todo_list_sub_title"><%= @todo_list.description %></p>
<div id="todo_items_wrapper">
 <%= render @todo_list.todo_items %>
 <div id="form">
  <%= render "todo_items/form" %>
 </div>
 <h1>Number of Tasks created</h1>
 <%= line_chart TodoItem.group_by_day(:created_at).count %>
</div>
<div class="links">
 <%= link_to 'Edit Task List', edit_event_todo_list_path(@event, @todo_list), {:style=>'color:#000000;', :class => "btnC"} %> | &nbsp;&nbsp;&nbsp;&nbsp;
 <%= link_to 'Delete Task List', event_todo_list_path(@event, @todo_list), method: :delete, data: { confirm: "Are you sure?"}, :style=>'color:#000000;', :class => "btnC" %> |&nbsp;&nbsp;&nbsp;&nbsp;
 <%= link_to 'Back', event_todo_lists_path(@event), {:style=>'color:#000000;', :class => "btnC"} %>
</div>