config/routes.rb
Rails.application.routes.default_url_options[:host] = "XXX"
Rails.application.routes.draw do

  root 'themes#index'
  get 'themes/index'
  get 'pages/about'
  get 'guestlists_imports/new'
  get 'guestlists_imports/create'
  get '/events/:event_id/guestlists/:id/response_page/:response', to: 'guestlists#response_page'

  #resources :guestlists_imports, only: [:new, :create]
  resources :locations
  #root to: 'events#index'
  root to: redirect('/events')
  root to: redirect('/guestlists')
  root to: redirect('/pages/about')
  #get 'guestlists'
  resources :events do
    resources :guestlists do
      patch :response_page, on: :member
      # match '/response_page', to:'events#guestlist#response_page', as: :response_page, :via => [:get,:post]
      collection do
        post :import
      end
    end
    resources :todo_lists do
      resources :todo_items do
        member do
          patch :complete
        end
      end
    end

    match '/landing_page', to:'events#landing_page', as: :landing_page, :via => [:get,:post]
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  # belongs_to :user
  has_many :guestlists , :dependent => :destroy
  accepts_nested_attributes_for :guestlists

  has_many :todo_lists, :dependent => :destroy
  has_many :todo_items, :through => :todo_lists
  accepts_nested_attributes_for :todo_lists
  accepts_nested_attributes_for :todo_items

  has_one_attached :cover_photo
  scope :sorted, lambda {order("created_at DESC")}

   validates :name, :location, :date_of_event, :rsvp_cut_off, presence: true
   validate :event_date_is_valid
   validate :cut_off_before_event

#Custom Validations to ensure dates selected do not conflict with eachother
  def event_date_is_valid
    if date_of_event < DateTime.now
      errors.add(:date_of_event, ": Uuum! Unfortunately you cannot create an event in the past.. This isn't back to the future. Please select a date that is still to come.")
    end
  end

  def cut_off_before_event
    if  date_of_event < rsvp_cut_off
      errors.add(:rsvp_cut_off, ": Wrong option")
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction

  # GET /events
  # GET /events.json
  def index
    @events = (Event.order(sort_column + " " + sort_direction))
    # @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])
  end

  def landing_page
    @event = Event.find(params[:event_id])
  end
  # GET /events/new
  def new
    @event = Event.new
    # @event.build_guestlist

  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)


    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully changed.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
  def sort_column
    Event.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    def sort_column
      Event.column_names.include?(params[:sort]) ? params[:sort] : "name"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :hostname, :date_of_event,:location,:address, :latitude, :longitude, :description,:rsvp_cut_off, :state, :cover_photo,
      :guestlist_attributes => [:name, :email ], :todo_list_attributes =>[:title, :description, :todo_item_attributes => [:content]])
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<% provide :head_tags do %>
<meta name='turbolinks-visit-control' content="reload">
<script>
  document.addEventListener("DOMContentLoaded", initMap2)
</script>
<% end %>

<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :hostname %>
    <%= form.text_field :hostname %>
  </div>

  <div class="field">
    <%= form.label :date_of_event %>
    <%= form.datetime_select(:date_of_event) %>
  </div>

  <div class="field">
    <%= form.label :location  %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :rsvp_cut_off %>
    <%= form.datetime_select(:rsvp_cut_off, :include_seconds => false ) %>
  </div>

  <div class="field">
    <%= form.label "Cover Photo" %>
    <%= form.file_field :cover_photo %>
  </div>

  <div class="field">
      <%= form.label :state, "Active/Draft" %> <br>
      <%= form.select :state, [['Draft Event', 'Draft'],['Active','Active'],['Cancelled','Cancelled']] %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

&nbsp;&nbsp;&nbsp;<%= link_to 'Show', @event, {:style=>'color:#WWWWWW;', :class => "btnC"} %> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<%= link_to 'Back', events_path, {:style=>'color:#WWWWWW;', :class => "btnC"} %>

app/views/events/index.html.erb
<h1>Events</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col"><%= sortable  "name" %></th>
      <th scope="col"><%= sortable  "date" %></th>
      <th scope="col"><%= sortable  "state", "Active/Draft" %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= event.date_of_event.strftime("%-d/%-m/%y %H:%M") %></td>
        <td><%= event.state %></td>
        <td><%= link_to 'Show', event_path(event) %></td>
        <td><%= link_to 'Guest List', event_guestlists_path(event) %></td>
        <td><%= link_to 'Task List', event_todo_lists_path(event) %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Delete', event, method: :delete, data: { confirm: 'Are you sure you want to delete this event' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div>
<br>
<%= link_to 'New Event', new_event_path, {:style=>'color:#WWWWWW;', :class => "btnC"} %>
</div>
<h1>Number of events created</h1>
<%= line_chart Event.group_by_day(:created_at).count %>

app/views/events/landing_page.erb
<div class="events show">

  <table summary="Event view">
    <h1><%=@event.name%></h1>
    <tr>
      <td><% if @event.cover_photo.attached? %>
        <image src="<%=(url_for(@event.cover_photo)) %>">
          <% end %>
      </td>
    </tr>

    <tr>
      <th>Date of Event</th>
      <td><%= @event.date_of_event.strftime("%-d/%-m/%y %H:%M %Z") %></td>
    </tr>
    <tr>
      <th>Description</th>
      <td><%= @event.description %></td>
    </tr>
    <tr>
      <th>Location</th>
      <td><%= @event.location %></td>
    </tr>


    <tr>
      <th>Respond by:</th>
      <td><%= @event.rsvp_cut_off.strftime("%-d/%-m/%y %H:%M %Z") %></td>
    </tr>
  </table>
</div>
<br>
<br>
<br>
<div>
</div>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

&nbsp;&nbsp;&nbsp;<%= link_to 'Back', events_path, {:style=>'color:#WWWWWW;', :class => "btnC"} %>

app/views/events/show.html.erb
<% provide :head_tags do %>
<meta name='turbolinks-visit-control' content='reload'>
<script>
  document.addEventListener("DOMContentLoaded", function() {
    initMap(<%=@event.latitude%>, <%@event.longitude%>)
  });
</script>
<% end %>

<div class="events show">
  <h2>Details for: <%=@event.name%></h2>
<br>
<br>
  <table summary="Event view" class="table table-hover">
    <tr>

      <td><% if @event.cover_photo.attached? %>
          <%= image_tag(url_for(@event.cover_photo), :width => "200", :height => "200") %>

          <% end %>
      </td>
    </tr>
    <tr class="table-active">
      <th>Host</th>
      <td><%= @event.hostname %></td>
    </tr>
    <tr class="table-active">
      <th>Time of Date of Event</th>
      <td><%= @event.date_of_event.strftime("%H:%M on the %-d/%-m/%y") %></td>
    </tr>
    <tr class="table-active">
      <th>Description</th>
      <td><%= @event.description %></td>
    </tr>
    <tr class="table-active">
      <th>Location</th>
      <td><%= @event.location %></td>
    </tr>


    <tr class="table-active">
      <th>Response Cut-Off</th>
      <td><%= @event.rsvp_cut_off.strftime("%-d/%-m/%y %H:%M") %></td>
    </tr>
    <!-- <tr>
      <th>Created</th>
      <td><%= @event.created_at.strftime("%-d/%-m/%y %H:%M") %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @event.updated_at.strftime("%-d/%-m/%y %H:%M") %></td>
    </tr> -->
  </table>


</div>
<br>
<br>

<div>
  <%= link_to 'Edit', edit_event_path(@event), {:style=>'color:#WWWWWW;', :class => "btnC"} %> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <%= link_to 'Back', events_path, {:style=>'color:#WWWWWW;', :class => "btnC"} %>
  <br>


<br>
<br>
  <%= link_to 'Take Me To The Guest List', event_guestlists_path(@event), {:style=>'color:#WWWWWW;', :class => "btnD"} %> <br><br><br>
  <%= link_to 'Take Me To The Task List', event_todo_lists_path(@event), {:style=>'color:#WWWWWW;', :class => "btnD"} %>
</div>