config/routes.rb
Rails.application.routes.default_url_options[:host] = "XXX"
Rails.application.routes.draw do

  root 'themes#index'
  get 'themes/index'
  get 'pages/about'
  get 'guestlists_imports/new'
  get 'guestlists_imports/create'
  get '/events/:event_id/guestlists/:id/response_page/:response', to: 'guestlists#response_page'

  #resources :guestlists_imports, only: [:new, :create]
  resources :locations
  #root to: 'events#index'
  root to: redirect('/events')
  root to: redirect('/guestlists')
  root to: redirect('/pages/about')
  #get 'guestlists'
  resources :events do
    resources :guestlists do
      patch :response_page, on: :member
      # match '/response_page', to:'events#guestlist#response_page', as: :response_page, :via => [:get,:post]
      collection do
        post :import
      end
    end
    resources :todo_lists do
      resources :todo_items do
        member do
          patch :complete
        end
      end
    end

    match '/landing_page', to:'events#landing_page', as: :landing_page, :via => [:get,:post]
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/guestlist.rb
class Guestlist < ApplicationRecord
  belongs_to :event, optional: true

  def self.to_csv(options = {})
  CSV.generate(options) do |csv|
    csv << column_names
    all.each do |guestlist|
      csv << guestlist.attributes.values_at(*column_names)
    end
  end
end

def self.import(file)
  spreadsheet = Roo::Spreadsheet.open(file.path)
  header = spreadsheet.row(1)
  (2..spreadsheet.last_row).each do |i|
    row = Hash[[header, spreadsheet.row(i)].transpose]
    guestlist = find_by(id: row["id"]) || new
    guestlist.attributes = row.to_hash
    guestlist.save!
  end
end

def self.open_spreadsheet(file)
  case File.extname(file.original_filename)
  when ".csv" then Roo::CSV.new(file.path, nil, :ignore)
  when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
  when ".xlsx" then Roo::Excelx.new(file.path, nil, :ignore)
  else raise "Unknown file type: #{file.original_filename}"
  end
end
validates :firstname, :lastname, :email, presence: true
end

app/controllers/guestlists_controller.rb
class GuestlistsController < ApplicationController
  before_action :set_event
  before_action :set_guestlist, only: [:show, :edit, :update, :destroy]

  helper_method :sort_column, :sort_direction
  # GET /guestlists
  # GET /guestlists.json
  # def index
  #   #@guestlists = Guestlist.all
  #   @guestlists = Guestlist.order(:name)
  #   respond_to do |format|
  #     format.html
  #     format.csv { send_data @guestlists.to_csv }
  #     format.xls { send_data @products.to_csv(col_sep: "\t") }
  #   # format.xlsx {
  #   #   response.headers[
  #   #     'Content-Disposition'
  #   #   ] = "attachment; filename='guestlists.xlsx'"
  #   # }
  #   # format.html { render :index }
  #   end
  # end

  def index
  @guestlists = @event.guestlists.order(sort_column + " " + sort_direction)
  # @guestlists=Guestlist.order(sort_column + " " + sort_direction)
  respond_to do |format|
    format.html
    format.csv { send_data @guestlists.to_csv }
    format.xls # { send_data @products.to_csv(col_sep: "\t") }
  end
end


def import
  begin
  @current_host = "http://" + request.host.to_s + ":" + request.port.to_s

  @event.guestlists.import(params[:file])
  @guestlists = Guestlist.where(event_id: @event.id)

  @guestlists.each do |g|
    #puts g.email
    GuestMailer.with(current_guest: g, current_event: @event, current_host: @current_host).guestlist_email.deliver_later
  end
  rescue => e
    redirect_to event_guestlists_path(@event), notice: "Guest List Has Successfully Been Added! Yay!"
  end
end

  def response_page
    @event = Event.find(params[:event_id])
    @guestlist = @event.guestlists.find(params[:id])
    @response_text = params[:response]
    @guestlist.response = @response_text
    @guestlist.save
  end


  # GET /guestlists/1
  # GET /guestlists/1.json
  def show
  end

  # GET /guestlists/new
  def new
    @guestlist = Guestlist.new
  end

  # GET /guestlists/1/edit
  def edit
  end

  # POST /guestlists
  # POST /guestlists.json
  def create
    @guestlist = @event.guestlists.new(guestlist_params)
    @current_host = "http://" + request.host.to_s + ":" + request.port.to_s
    respond_to do |format|
      if @guestlist.save
        format.html { redirect_to event_guestlists_url, notice: 'Guest was successfully created.' }
        format.json { render :show, status: :created, location: @guestlist }
        GuestMailer.with(current_guest: @guestlist, current_event: @event, current_host: @current_host).guestlist_email.deliver_later
      else
        format.html { render :new }
        format.json { render json: @guestlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guestlists/1
  # PATCH/PUT /guestlists/1.json
  def update
    respond_to do |format|
      if @guestlist.update(guestlist_params)
        format.html { redirect_to event_guestlists_path(@event), notice: 'Guest was successfully updated.' }
        format.json { render :show, status: :ok, location: @guestlist }
      else
        format.html { render :edit }
        format.json { render json: @guestlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guestlists/1
  # DELETE /guestlists/1.json
  def destroy
    @guestlist.destroy
    respond_to do |format|
      format.html { redirect_to event_guestlists_path(@event), notice: 'Guest was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    def sort_column
      Guestlist.column_names.include?(params[:sort]) ? params[:sort] : "firstname"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end

    def set_guestlist
      @guestlist = @event.guestlists.find(params[:id])
    end

    def set_event
      @event = Event.find(params[:event_id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def guestlist_params
      params.require(:guestlist).permit(:firstname, :lastname, :email, :response, :dietary_requirements, :event_id)
    end
end

app/helpers/guestlists_helper.rb
module GuestlistsHelper
end

app/views/guestlists/_form.html.erb
<%= form_with(model: [@event, guestlist], local: true) do |form| %>
  <% if guestlist.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% guestlist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :firstname %>
    <%= form.text_field :firstname %>
  </div>

  <div class="field">
    <%= form.label :lastname %>
    <%= form.text_field :lastname %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
      <%= form.label :response %> <br>
      <%= form.select :response, [['No Response', 'No Response'],['I will be there!','Yes'],['Eish! I can not make it','No'],['I am not so sure yet','Maybe']] %>
  </div>

  <div class="field">
      <%= form.label :dietary_requirements %> <br>
      <%= form.select :dietary_requirements, [['I Eat Everything!', 'No Requirements'],['Vegetarian','Vegetarian'],['Vegan','Vegan'],['Halaal','Halaal'],['Kosher','Kosher']] %>
  </div>

  <!-- <div class="field">
    <%= form.label :event_id %>
    <%= form.text_field :event_id %>
  </div> -->

<br>

  <div class="actions">
    <%= form.submit "Save Guest"%>
  </div>
<% end %>

app/views/guestlists/_guestlist.html.erb
<p><%= guestlists.id %></p>

<p>Edit this guest:</p>
<%= render 'guestlists/table', guestlist: guestlist %>

<p><%= link_to "Remove guest", event_guestlist_path(@event, guestlist), method: :delete %></p>

<hr>

app/views/guestlists/edit.html.erb
<h1>Editing Guest</h1>

<%= render 'form', guestlist: @guestlist %>

<br><br>
  &nbsp;&nbsp;&nbsp;&nbsp;<%= link_to 'Back', event_guestlists_path(@event), {:style=>'color:#WWWWWW;', :class => "btnC"} %>

app/views/guestlists/index.html.erb
<h1>Guestlists for <%= @event.name %></h1>

<p>
  Download:
  <%= link_to "CSV", event_guestlists_path(format: "csv") %> |
  <%= link_to "Excel", event_guestlists_path(format: "xls") %>
</p>

<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col"><%= sortable  "firstname" %></th>
      <th scope="col"><%= sortable  "lastname" %></th>
      <th scope="col"><%= sortable  "email" %></th>
      <th scope="col"><%= sortable  "response" %></th>
      <th scope="col"><%= sortable  "dietary_requirements" %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @event.guestlists.each do |guestlist| %>
      <tr>
        <td><%= guestlist.firstname %></td>
        <td><%= guestlist.lastname %></td>
        <td><%= guestlist.email %></td>
        <td><%= guestlist.response %></td>
        <td><%= guestlist.dietary_requirements %></td>
        <td><%= link_to 'Edit', edit_event_guestlist_path(@event, guestlist) %></td>
        <td><%= link_to 'Delete', event_guestlist_path(@event, guestlist), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<br>
<br>
<%= link_to 'Add Another Guest', new_event_guestlist_path(@event), {:style=>'color:#WWWWWW;', :class => "btnC"} %> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<%= link_to 'Back', event_path(@event), {:style=>'color:#WWWWWW;', :class => "btnC"} %>  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<%= link_to 'Back To All Events', events_path, {:style=>'color:#WWWWWW;', :class => "btnC"} %>

<br>

<h1>Number of responses by guests</h1>
<%= pie_chart @event.guestlists.group(:response).count %>
<br>
<h1>Dietary Requirements</h1>
<%= pie_chart @event.guestlists.group(:dietary_requirements).count %>

<h2>Import Guestlist</h2>
<%= form_tag import_event_guestlists_path(@event), multipart: true do %>
  <%= file_field_tag :file %>

  <%= submit_tag "Import Guest List" %>
<% end %>
<br>

app/views/guestlists/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">id</Data></Cell>
        <Cell><Data ss:Type="String">firstname</Data></Cell>
        <Cell><Data ss:Type="String">lastname</Data></Cell>
        <Cell><Data ss:Type="String">email</Data></Cell>
        <Cell><Data ss:Type="String">response</Data></Cell>
        <Cell><Data ss:Type="String">dietary_requirements</Data></Cell>
      </Row>
    <% @guestlists.each do |guestlist| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= guestlist.id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= guestlist.firstname %></Data></Cell>
        <Cell><Data ss:Type="String"><%= guestlist.lastname %></Data></Cell>
        <Cell><Data ss:Type="String"><%= guestlist.email %></Data></Cell>
        <Cell><Data ss:Type="String"><%= guestlist.response %></Data></Cell>
        <Cell><Data ss:Type="String"><%= guestlist.dietary_requirements %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/guestlists/new.html.erb
<h1>Add a Guest to <%= @event.name %> </h1>

<%= render 'form', guestlist: @guestlist %>


&nbsp;&nbsp;&nbsp;<%= link_to 'Back', event_guestlists_path(@event), {:style=>'color:#WWWWWW;', :class => "btnC"} %>

app/views/guestlists/response_page.html.erb
<p id="notice"><%= notice %></p>

<h1>Thank you <%= @guestlist.name %> for your response</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

        <p> Event Name: <%= @event.name %> </p>

        <p> Event Description: <%= @event.description %> </p>

        <p> You have responded: <%= @response_text %> </p>

  </tbody>
</table>
<br>

app/views/guestlists/show.html.erb
<p>
  <strong>First Name:</strong>
  <%= @guestlist.firstname %>
</p>
<p>
  <strong>Last Name:</strong>
  <%= @guestlist.lastname %>
</p>
<p>
  <strong>Email:</strong>
  <%= @guestlist.email %>
</p>

<p>
  <strong>Response:</strong>
  <%= @guestlist.response %>
</p>
<p>
  <strong>Dietary Requirements:</strong>
  <%= @guestlist.dietary_requirements %>
</p>

<%= link_to 'Edit', edit_event_guestlist_path(@event, @guestlist), {:style=>'color:#WWWWWW;', :class => "btnC"} %> |
<%= link_to 'Back', event_guestlists_path(@event), {:style=>'color:#WWWWWW;', :class => "btnC"} %>